[package]
name = "docker"
version = "0.1.6"
edition = "2021"
authors = ["poohlaha"]
license = "MIT/Apache-2.0"
description = "Package the docker image and modify the kubectl pod ."
homepage = "https://github.com/poohlaha/rust-tools/tree/main/packages/docker"
repository = "https://github.com/poohlaha/rust-tools/tree/main/packages/docker"
readme = "README.md"
keywords = ["docker"]

[dependencies]
thiserror = "1.0"
log = "0.4"
ssh2 = "0.9"
handlers = {git = "https://github.com/poohlaha/rust-tools", branch = "main", package = "handlers"}
sftp = {git = "https://github.com/poohlaha/rust-tools", branch = "main", package = "sftp"}
