[package]
name = "request-http"
version = "0.1.1"
edition = "2021"
authors = ["poohlaha"]
license = "MIT/Apache-2.0"
description = "Send http or https request."
homepage = "https://github.com/poohlaha/rust-tools/tree/main/packages/http"
repository = "https://github.com/poohlaha/rust-tools/tree/main/packages/http"
readme = "README.md"
keywords = ["http", "request-http", "request"]

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json", "multipart", "blocking"] }
colored = "2.0"
indicatif = "0.17"
thiserror = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "benchmarks"
harness = false

[package.metadata.docs.rs]
targets = ["src/lib.rs"]
