[package]
name = "handlers"
version = "0.1.4"
edition = "2021"
authors = ["poohlaha"]
license = "MIT/Apache-2.0"
description = "sftp file upload, File operation and some other public methods."
homepage = "https://github.com/poohlaha/rust-tools/tree/main/packages/handlers"
repository = "https://github.com/poohlaha/rust-tools/tree/main/packages/handlers"
readme = "README.md"
keywords = ["handlers", "file", "utils", "command"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "2.1.6"
fs_extra = "1.3"
chrono = "0.4"
crypto-hash = "0.3"
log = "0.4"
thiserror = "1.0"